name = "sonada"
description = "A perlin noise animation in your terminal written in Ada."
version = "0.1.0-dev"

authors = ["Vianney Hervy"]
maintainers = ["Vianney Hervy <vian.hervy@gmail.com>"]
maintainers-logins = ["sully-vian"]
licenses = "GPL-3.0-only"
website = "https://github.com/sully-vian/sonada"
executables = ["./bin/sonada"]

[build-switches]
"*".ada_version = "ada2022"
"*".style_checks = ["-gnatyC"]
release.optimization = ["-O2", "-gnatn"]
