name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Alire
        run: make setup-alire

      - name: Build release
        run: make

      - name: Test binary
        run: |
          ls -lh bin/
          file bin/sonada
          ! ldd bin/sonada
          ./bin/sonada --help

      - name: Upload artifact
        if: ${{env.ACT != 'true' }} # skip upload artifact if running in act
        uses: actions/upload-artifact@v4
        with:
          name: sonada-linux-x86_64
          path: bin/sonada
          retention-days: 30
