name: Release

on:
  workflow_dispatch: # only manual

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LDD Linker
        run: |
          sudo apt update
          sudo apt install -y lld

      - name: Install Alire
        uses: alire-project/setup-alire@v4

      - name: Build release
        run: make

      - name: Prepare artifacts
        run: |
          BIN=bin/sonada
          sha256sum "$BIN" > sonada.sha256
          ls -lh "$BIN" sonada.sha256

      - name: Get release metadata
        id: metadata
        run: |
          RELEASE_DATE=$(date +'%Y-%m-%d')
          echo "tag_name=release-$RELEASE_DATE" >> $GITHUB_OUTPUT
          echo "release_name=Sonada Release $RELEASE_DATE" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.metadata.outputs.tag_name }}
          name: ${{ steps.metadata.outputs.release_name }}
          files: |
            bin/sonada
            sonada.sha256
